name: Build & Deploy Storybook
on:
  push:
    branches: [dev]
    paths: ['shared/ui/src/**']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build ðŸ”§
        # This needs an Acces Token stored as "GH_TOKEN" ðŸ‘‡
        run: |
          cd shared/ui
          yarn install
          yarn run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
